import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
import java.lang.NullPointerException;
//import com.mysql.jdbc.exceptions.MySQLIntegrityConstraintViolationException;
import java.lang.NullPointerException;
import java.net.Socket;
import java.util.logging.Level;
import java.util.logging.Logger;
import static javax.swing.JOptionPane.NO_OPTION;
import static javax.swing.JOptionPane.YES_OPTION;
public class Program extends javax.swing.JFrame {

   Connection con; //establish connection
  PreparedStatement statement; //execute sql statement more of optimised
  Statement st;//execute sql statement less of optimised
  String cs; //holding path of the database
  String user;//username for the database
  String password;//password for the database
  String query;
  ResultSet rs;
  String records;
  Boolean bnext = false;
  Boolean bprevious = true;
  
   ObjectOutputStream clientObjectStreamWriter;
  ObjectInputStream clientObjectStreamReader, isReader;
  
  Socket sock;
  
  Program_SC SerialObj;
    public Program() {
        go();
        initComponents();
        
          con = null;
    st = null;
    statement = null;
    
    cs = "jdbc:mysql://localhost:3306/admission";
    user = "root";
    password = "peacebewithyouall2020";
    }
    
    public void go() {
        try{
            
            sock = new Socket("127.0.0.1",50000);
        SerialObj = new Program_SC();
        
        clientObjectStreamWriter = new ObjectOutputStream(sock.getOutputStream());
        clientObjectStreamReader = new ObjectInputStream(sock.getInputStream());
        System.out.println("networking established");
        
        Thread t = new Thread((Runnable) new ClientRunnable());

	t.start();
	System.out.println("got a connection");
        }
        catch(java.net.ConnectException e){
            JOptionPane.showMessageDialog(null,"CONNECTION REFUSED!! SERVER DOWN MAYBE");
            System.exit(0);
                 } catch (IOException ex) {
       
    }
    }
    
    
     public class ClientRunnable implements Runnable{

        @Override
        public void run() {
            try{
                while((SerialObj =  (Program_SC)clientObjectStreamReader.readObject()) != null ){
                    
                    txtProgram_ID.setText(SerialObj.ProgID);
                    txtProgramName.setText(SerialObj.ProgName);
                    txtDepartmentID.setText(SerialObj.DepID);
                    
                    
                    
                    go();
                }
            }
             catch (IOException ex) {
                        ex.printStackTrace();
                    }
            catch (ClassNotFoundException ex) {
                        ex.printStackTrace();
                    }
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblProgram_ID = new javax.swing.JLabel();
        lblProgramName = new javax.swing.JLabel();
        lblDepartment_ID = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        btnFind = new javax.swing.JButton();
        txtProgram_ID = new javax.swing.JTextField();
        txtProgramName = new javax.swing.JTextField();
        txtDepartmentID = new javax.swing.JTextField();
        Firstbtn = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        btnLast = new javax.swing.JButton();
        Previousbtn = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        kGradientPanel1 = new keeptoo.KGradientPanel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblProgram_ID.setFont(new java.awt.Font("DejaVu Serif", 1, 18)); // NOI18N
        lblProgram_ID.setText("Program ID");
        getContentPane().add(lblProgram_ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 68, 144, 60));

        lblProgramName.setFont(new java.awt.Font("DejaVu Serif", 1, 18)); // NOI18N
        lblProgramName.setText("Program Name");
        getContentPane().add(lblProgramName, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 186, 166, 66));

        lblDepartment_ID.setFont(new java.awt.Font("DejaVu Serif", 1, 18)); // NOI18N
        lblDepartment_ID.setText("Department ID");
        getContentPane().add(lblDepartment_ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 304, 199, 67));

        btnSave.setFont(new java.awt.Font("DejaVu Serif", 1, 18)); // NOI18N
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        getContentPane().add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 434, 80, 41));

        btnFind.setFont(new java.awt.Font("DejaVu Serif", 1, 18)); // NOI18N
        btnFind.setText("Find");
        btnFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindActionPerformed(evt);
            }
        });
        getContentPane().add(btnFind, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 434, 77, 41));

        txtProgram_ID.setFont(new java.awt.Font("DejaVu Serif", 0, 18)); // NOI18N
        txtProgram_ID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProgram_IDActionPerformed(evt);
            }
        });
        getContentPane().add(txtProgram_ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(223, 69, 421, 60));

        txtProgramName.setFont(new java.awt.Font("DejaVu Serif", 0, 18)); // NOI18N
        txtProgramName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProgramNameActionPerformed(evt);
            }
        });
        getContentPane().add(txtProgramName, new org.netbeans.lib.awtextra.AbsoluteConstraints(223, 187, 421, 66));

        txtDepartmentID.setFont(new java.awt.Font("DejaVu Serif", 0, 18)); // NOI18N
        txtDepartmentID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDepartmentIDActionPerformed(evt);
            }
        });
        getContentPane().add(txtDepartmentID, new org.netbeans.lib.awtextra.AbsoluteConstraints(223, 304, 421, 67));

        Firstbtn.setFont(new java.awt.Font("DejaVu Serif", 1, 18)); // NOI18N
        Firstbtn.setText("First");
        Firstbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FirstbtnActionPerformed(evt);
            }
        });
        getContentPane().add(Firstbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(181, 434, 81, 41));

        btnNext.setFont(new java.awt.Font("DejaVu Serif", 1, 18)); // NOI18N
        btnNext.setText("Next");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });
        getContentPane().add(btnNext, new org.netbeans.lib.awtextra.AbsoluteConstraints(268, 434, 78, 41));

        btnLast.setFont(new java.awt.Font("DejaVu Serif", 1, 18)); // NOI18N
        btnLast.setText("Last");
        btnLast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLastActionPerformed(evt);
            }
        });
        getContentPane().add(btnLast, new org.netbeans.lib.awtextra.AbsoluteConstraints(352, 434, 81, 41));

        Previousbtn.setFont(new java.awt.Font("DejaVu Serif", 1, 18)); // NOI18N
        Previousbtn.setText("Previous");
        Previousbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PreviousbtnActionPerformed(evt);
            }
        });
        getContentPane().add(Previousbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(439, 434, -1, 41));

        btnDelete.setFont(new java.awt.Font("DejaVu Serif", 1, 18)); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(549, 434, 104, 41));

        kGradientPanel1.setkEndColor(java.awt.Color.white);
        kGradientPanel1.setkStartColor(java.awt.Color.blue);

        jButton1.setText("B");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addComponent(jButton1)
                .addGap(0, 680, Short.MAX_VALUE))
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addComponent(jButton1)
                .addGap(0, 462, Short.MAX_VALUE))
        );

        getContentPane().add(kGradientPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 490));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
         
          String s1 =  txtProgram_ID.getText();
String s2 =  txtProgramName.getText();
String s3 =  txtDepartmentID.getText();


try {
    
    Class.forName("com.mysql.jdbc.Driver");//register JDBC driver
    
    con = DriverManager.getConnection(cs,user,password);
    st = con.createStatement();
    query = "INSERT INTO Program (Program_id,Program_Name,Department_Department_id) VALUES ('"+s1+"','"+s2+"','"+s3+"')";
    st. executeUpdate(query);
    JOptionPane.showMessageDialog(null,"Record saved successfully");
    
    txtProgram_ID.setText("");
     txtProgramName.setText("");
     txtDepartmentID.setText("");
     
     
     
     txtProgram_ID.requestFocus();  //setting focus on REGNO   
}
catch (SQLException ex){
    ex.printStackTrace();//displays information about SQL statement incase you typed table name or field name that is not existing
    //it displays where the error may be
}
catch (ClassNotFoundException e){
  e.printStackTrace();  //checks if the driver  is not configured
}

finally{
    
    try{
        if(st != null)
        {
            st.close();
        }
        if(con != null){
            con.close();
        }
    }
        catch (SQLException ex){
                ex.printStackTrace();
                }
    }

        

    }//GEN-LAST:event_btnSaveActionPerformed

    private void txtProgram_IDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProgram_IDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProgram_IDActionPerformed

    private void txtDepartmentIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDepartmentIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDepartmentIDActionPerformed

    private void btnFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindActionPerformed
        // TODO add your handling code here:
        try {
    
    Class.forName("com.mysql.cj.jdbc.Driver");
    
    con = DriverManager.getConnection(cs,user,password);
    
    
     PreparedStatement st = con.prepareStatement("SELECT * FROM Program WHERE   Program_id ='"+txtProgram_ID.getText()+"'", 
  ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);
    ResultSet rs = st.executeQuery();
    
    if(rs.first()){
       txtProgram_ID.setText(rs.getString("Program_id")); 
       txtProgramName.setText(rs.getString("Program_Name"));
       txtDepartmentID.setText(rs.getString("Department_Department_id"));
    }
    else{
        JOptionPane.showMessageDialog(null,"Record not found");
         txtProgram_ID.setText("");
         txtProgram_ID.requestFocus();
    }
    
    
       
}
catch (SQLException ex){
    ex.printStackTrace();
}
catch (ClassNotFoundException e){
  e.printStackTrace();  
}

finally{
    
    try{
        if(st != null)
        {
            st.close();
        }
        if(con != null){
            con.close();
        }
    }
        catch (SQLException ex){
                ex.printStackTrace();
                }
    }

        
    }//GEN-LAST:event_btnFindActionPerformed

    private void FirstbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FirstbtnActionPerformed
        // TODO add your handling code here:
        try {
    
    Class.forName("com.mysql.cj.jdbc.Driver");
    
    con = DriverManager.getConnection(cs,user,password);
    st = con.createStatement();
    //query = "SELECT * FROM students ";
    //st. executeUpdate(query);
    //JOptionPane.showMessageDialog(null,"Record saved");
    PreparedStatement st = con.prepareStatement("SELECT * FROM Program", 
  ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);
    ResultSet rs = st.executeQuery();
    
    
    
    if(rs.first()){
       txtProgram_ID.setText(rs.getString("Program_id")); 
       txtProgramName.setText(rs.getString("Program_Name"));
       txtDepartmentID.setText(rs.getString("Department_Department_id"));
       
    }
    else{
        JOptionPane.showMessageDialog(null,"Record not found");
        txtProgram_ID.setText("");
        txtProgram_ID.requestFocus();
    }
    
    
       
}
catch (SQLException ex){
    ex.printStackTrace();
}
catch (ClassNotFoundException e){
  e.printStackTrace();  
}

finally{
    
    try{
        if(st != null)
        {
            st.close();
        }
        if(con != null){
            con.close();
        }
    }
        catch (SQLException ex){
                ex.printStackTrace();
                }
    }
    }//GEN-LAST:event_FirstbtnActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        // TODO add your handling code here:
         try {
   
    
    Class.forName("com.mysql.cj.jdbc.Driver");
    
    con = DriverManager.getConnection(cs,user,password);
    st = con.createStatement();
    PreparedStatement st = con.prepareStatement("SELECT * FROM Program", 
  ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);
    if(!bnext){
      rs = st.executeQuery();  
       rs.first();
   
       txtProgram_ID.setText(rs.getString("Program_id")); 
       txtProgramName.setText(rs.getString("Program_Name"));
       txtDepartmentID.setText(rs.getString("Department_Department_id"));
       
       bnext = true;
    }
    else if(rs.next()){
        
        txtProgram_ID.setText(rs.getString("Program_id")); 
       txtProgramName.setText(rs.getString("Program_Name"));
       txtDepartmentID.setText(rs.getString("Department_Department_id"));
       
     bnext = true;
      
    }
    
    
       
}
catch (SQLException ex){
    ex.printStackTrace();
}
catch (ClassNotFoundException e){
  e.printStackTrace();  
}

    }//GEN-LAST:event_btnNextActionPerformed

    private void btnLastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLastActionPerformed
        // TODO add your handling code here:
        try {
    
    Class.forName("com.mysql.cj.jdbc.Driver");
    
    con = DriverManager.getConnection(cs,user,password);
    st = con.createStatement();
    PreparedStatement st = con.prepareStatement("SELECT * FROM Program", 
  ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);
    ResultSet rs = st.executeQuery();
    
    if(rs.last()){
       txtProgram_ID.setText(rs.getString("Program_id")); 
       txtProgramName.setText(rs.getString("Program_Name"));
       txtDepartmentID.setText(rs.getString("Department_Department_id"));
       
    }
    else{
        JOptionPane.showMessageDialog(null,"Record not found");
        txtProgram_ID.setText("");
        txtProgram_ID.requestFocus();
    }
    
    
       
}
catch (SQLException ex){
    ex.printStackTrace();
}
catch (ClassNotFoundException e){
  e.printStackTrace();  
}

finally{
    
    try{
        if(st != null)
        {
            st.close();
        }
        if(con != null){
            con.close();
        }
    }
        catch (SQLException ex){
                ex.printStackTrace();
                }
    }
    }//GEN-LAST:event_btnLastActionPerformed

    private void PreviousbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PreviousbtnActionPerformed
        // TODO add your handling code here:
        
        try {
    
    Class.forName("com.mysql.cj.jdbc.Driver");
    
    con = DriverManager.getConnection(cs,user,password);
    st = con.createStatement();
    PreparedStatement st = con.prepareStatement("SELECT * FROM Program", 
  ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);
    ResultSet rs = st.executeQuery();
    
    if(rs.last()){
       txtProgram_ID.setText(rs.getString("Program_id")); 
       txtProgramName.setText(rs.getString("Program_Name"));
       txtDepartmentID.setText(rs.getString("Department_Department_id"));
       
    }
    else{
        JOptionPane.showMessageDialog(null,"Record not found");
        txtProgram_ID.setText("");
        txtProgram_ID.requestFocus();
    }
    
    
       
}
catch (SQLException ex){
    ex.printStackTrace();
}
catch (ClassNotFoundException e){
  e.printStackTrace();  
}

finally{
    
    try{
        if(st != null)
        {
            st.close();
        }
        if(con != null){
            con.close();
        }
    }
        catch (SQLException ex){
                ex.printStackTrace();
                }
    }
        try {
   
    
    Class.forName("com.mysql.cj.jdbc.Driver");
    
    con = DriverManager.getConnection(cs,user,password);
    st = con.createStatement();
    
    PreparedStatement st = con.prepareStatement("SELECT * FROM Program", 
  ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);
    
    if(!bprevious){
      rs = st.executeQuery();  
       rs.last();
   
       txtProgram_ID.setText(rs.getString("Program_id")); 
       txtProgramName.setText(rs.getString("Program_Name"));
       txtDepartmentID.setText(rs.getString("Department_Department_id"));
       
       bprevious = true;
    }
    else if(rs.previous()){
        
        txtProgram_ID.setText(rs.getString("Program_id")); 
       txtProgramName.setText(rs.getString("Program_Name"));
       txtDepartmentID.setText(rs.getString("Department_Department_id"));
       
     bnext = true;
      
    }
    
    
       
}
catch (SQLException ex){
    ex.printStackTrace();
}
catch (ClassNotFoundException e){
  e.printStackTrace();  
}


    }//GEN-LAST:event_PreviousbtnActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        int answer = JOptionPane.showConfirmDialog(this,"Are you sure you want to delete?","confirm",JOptionPane.YES_NO_OPTION);
        
    if(answer == YES_OPTION){
     try {
    
    Class.forName("com.mysql.cj.jdbc.Driver");
    
    con = DriverManager.getConnection(cs,user,password);
    st = con.createStatement();
    
    
    PreparedStatement st = con.prepareStatement("DELETE  FROM Program WHERE   Program_id ='"+txtProgram_ID.getText()+"'", 
  ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);
    
     if(st.executeUpdate() == 1){
         JOptionPane.showMessageDialog(null,"Record with RegNo: '"+txtProgram_ID.getText()+"'deleted");
         
     }
     else if(st.executeUpdate() == 0){
         JOptionPane.showMessageDialog(null,"Record with RegNo: '"+txtProgram_ID.getText()+"'does not exist");
     }
  }
     
catch (SQLException ex){
    ex.printStackTrace();
}
catch (ClassNotFoundException e){
  e.printStackTrace();  
}

finally{
    
    try{
        if(st != null)
        {
            st.close();
        }
        if(con != null){
            con.close();
        }
    }
        catch (SQLException ex){
                ex.printStackTrace();
                }
    }
    
    
    }                                            
else if(answer == NO_OPTION){
          txtProgram_ID.requestFocus();
          return ;
      }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void txtProgramNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProgramNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProgramNameActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Main_page ma = new Main_page();
        ma.setVisible(true);
        this.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String []args) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Program.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Program.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Program.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Program.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Program().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Firstbtn;
    private javax.swing.JButton Previousbtn;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnFind;
    private javax.swing.JButton btnLast;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton jButton1;
    private keeptoo.KGradientPanel kGradientPanel1;
    private javax.swing.JLabel lblDepartment_ID;
    private javax.swing.JLabel lblProgramName;
    private javax.swing.JLabel lblProgram_ID;
    private javax.swing.JTextField txtDepartmentID;
    private javax.swing.JTextField txtProgramName;
    private javax.swing.JTextField txtProgram_ID;
    // End of variables declaration//GEN-END:variables
}
